CREATE TABLE IF NOT EXISTS public.wallet_gift_transfers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unique_gift_id bigint NOT NULL REFERENCES public.unique_star_gifts(id) ON DELETE RESTRICT,
    action varchar(16) NOT NULL,
    wallet_name text NOT NULL DEFAULT '',
    wallet_address text NOT NULL DEFAULT '',
    previous_wallet_address text NOT NULL DEFAULT '',
    previous_owner_peer_type text NOT NULL DEFAULT '',
    previous_owner_peer_id bigint NOT NULL DEFAULT 0,
    previous_host_peer_type text NOT NULL DEFAULT '',
    previous_host_peer_id bigint NOT NULL DEFAULT 0,
    actor_user_id bigint NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT wallet_gift_transfers_action_check CHECK (action IN ('bind', 'release')),
    CONSTRAINT wallet_gift_transfers_bind_check CHECK (
        (action = 'bind' AND wallet_name <> '' AND wallet_address <> '')
        OR (action = 'release' AND previous_wallet_address <> '')
    )
);
CREATE INDEX IF NOT EXISTS wallet_gift_transfers_gift_idx
    ON public.wallet_gift_transfers(unique_gift_id, id DESC);
